# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bef9debb23a3fc1685bae6b47d314c9e8a995b48d04c12fbdea341f09361d73ce2e25ecedcc67abebf0af3105c0bc5bf34cdbebf67dac09828b9a5bb75072fef

test:
  secret_key_base: 6662c276ecf320241833bb925067bea7d40a968d91a764c4ebbbad416b4aa9f8842412e34cf253fc02191f7fb1670f07e1f65c13b466a9be4de3abe3f1a06ec8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
